<a class="page-back" href="/">&larr;</a>
<h1 class="page-header">
    <?php echo $product->getName(); ?>
</h1>

<img class="product-view_image" src="<?php echo $product->getImage(); ?>" />
<div class="product-view_sku"><?php echo $product->getSku(); ?></div>
<div>
    <span
        class="product-item_price <?php if ($product->isSpecialPriceApplied()): ?>old-price<?php endif; ?>">
        $<?php echo $product->getPrice(); ?>
    </span>
    <?php if($product->isSpecialPriceApplied()): ?>
        <span class="product-item_price">$<?php echo $product->getSpecialPrice(); ?></span>
    <?php endif; ?>
</div>

