<!DOCTYPE html>
<html>
<head>
    <title>Student Webstore</title>
</head>
<body>
<h1>Our Product List</h1>
<ul>
    <?php foreach ($products as $_product): ?>
        <li>
            <a href="?page=product_view&id=<?php echo $_product->getId(); ?>">
                <img src="<?php echo $_product->getImage(); ?>" />
                <h2><?php echo $_product->getName(); ?></h2>
                <span><?php echo $_product->getSku(); ?></span>
                <span><?php echo $_product->getPrice(); ?></span>
                <span><?php echo $_product->getSpecialPrice(); ?></span>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
</body>
</html>
